// <auto-generated />
namespace Projet_pilate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MajIndexUniqueTableMission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MajIndexUniqueTableMission));
        
        string IMigrationMetadata.Id
        {
            get { return "202005011137239_MajIndexUniqueTableMission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
