// <auto-generated />
namespace Projet_pilate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class odmAjouter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(odmAjouter));
        
        string IMigrationMetadata.Id
        {
            get { return "202008030657026_odmAjouter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
