// <auto-generated />
namespace Projet_pilate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MajIndexUniqueTableConsultant : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MajIndexUniqueTableConsultant));
        
        string IMigrationMetadata.Id
        {
            get { return "202005150955373_MajIndexUniqueTableConsultant"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
